### ISSUE TITLE
I got a question in training bam model.AttributeError: 'Namespace' object has no attribute 'weighted'

### ISSUE THREAD

**Issue by louxiantuo** [justchenhao/STANet#11]
Traceback (most recent call last):
  File "./train.py", line 109, in <module>
    model = create_model(opt)      # create a model given opt.model and other options
  File "/home/louxiantuo/STANet/models/__init__.py", line 65, in create_model
    instance = model(opt)
  File "/home/louxiantuo/STANet/models/CDFA_model.py", line 53, in __init__
    self.isweighted = opt.weighted
AttributeError: 'Namespace' object has no attribute 'weighted'

What should I do?

**Comment by louxiantuo** [comment]
And then I delete 
#self.isweighted = opt.weighted
but 

RuntimeError: CUDA out of memory. Tried to allocate 64.00 GiB (GPU 0; 6.00 GiB total capacity; 402.79 MiB already allocated; 3.81 GiB free; 498.00 MiB reserved in total by PyTorch)

64GB???

**Comment by raminrahimi6970** [comment]
Hi
Edit your batch-size to 4 or 2 or less

**Comment by raminrahimi6970** [comment]
i guess we should run PAM with CDF0 not with CDFA

**Comment by louxiantuo** [comment]
> Hi
> Edit your batch-size to 4 or 2 or less

I edit my batch-size to less,4,2,1.But problem is same.64G.....
If use CDF0,the results are same with base.......

Are u test it with model PAM?

**Comment by raminrahimi6970** [comment]
I train with my data with PAM and CDF0 ....my train not end

**Comment by louxiantuo** [comment]
> I train with my data with PAM and CDF0 ....my train not end

Do u find the epoch of time is same?So both of model are same.

**Comment by raminrahimi6970** [comment]
you can run it on cpu if your test the code

**Comment by louxiantuo** [comment]
> you can run it on cpu if you are test the code

Do u have an e-mail or wechat account?
Nop,when I test,I find the same problem about cuda out of memroy

**Comment by raminrahimi6970** [comment]
> > you can run it on cpu if you are test the code
> 
> Do u have an e-mail or wechat account?
> Nop,when I test,I find the same problem about cuda out of memroy

raminram6970@gmail.com

**Comment by raminrahimi6970** [comment]
I true understand you say we should run PAM with CDFA?

**Comment by louxiantuo** [comment]
I send somthing to your email

**Comment by justchenhao** [comment]
Has it fixed? Cause I could run the PAM on the GPU 1080Ti with the cropsize=256 and batchsize=4.

**Comment by Max-zc** [comment]
Hi, I met the problem too. how to fix it?

**Comment by justchenhao** [comment]
@Max-zc 1, for the 'weight' problem, the repository has been updated to fix this issue. 2, for the 'out of memory', you could run the PAM on the GPU 1080Ti with the cropsize=256 and batchsize=4.

**Comment by justchenhao** [comment]
Close for now. Feel free to reopen if you still have questions.
