### ISSUE TITLE
about model CDF0 and CDFA

### ISSUE THREAD

**Issue by hktxt** [justchenhao/STANet#14]
hi, thanks for your work. 
BAM and PAM are the attention modules which were described in the paper.
feature ectractor is modified resnet18.
However, what is CDF0? and CDFA?

**Comment by justchenhao** [comment]
Thanks for your attention.  CDF0 and CDFA are two implementations within the programming perspective. You could use CDF0 to run the base model, and use CDFA to run either the BAM or PAM.
