### ISSUE TITLE
metrics always 0.0

### ISSUE THREAD

**Issue by hktxt** [justchenhao/STANet#15]
I use this repo to trian my own dataset.
I set the num_class = 2(change/unchange).
model converged normally.
but the **precision_1**/**recall_1**/**F1_1** does not change, always 0.

val_log.txt:
(epoch: 1) Overall_Acc: 0.971 Mean_IoU: 0.486 0: 0.971 1: 0.000 precision_1: 0.000 recall_1: 0.000 F1_1: 0.000 
================ val acc (Sun Jun 28 15:31:51 2020) ================
(epoch: 2) Overall_Acc: 0.977 Mean_IoU: 0.489 0: 0.977 1: 0.000 precision_1: 0.000 recall_1: 0.000 F1_1: 0.000 
================ val acc (Sun Jun 28 15:32:57 2020) ================
(epoch: 3) Overall_Acc: 0.979 Mean_IoU: 0.490 0: 0.979 1: 0.000 precision_1: 0.000 recall_1: 0.000 F1_1: 0.000 
================ val acc (Sun Jun 28 15:34:01 2020) ================
(epoch: 4) Overall_Acc: 0.983 Mean_IoU: 0.491 0: 0.983 1: 0.000 precision_1: 0.000 recall_1: 0.000 F1_1: 0.000 
================ val acc (Sun Jun 28 15:35:06 2020) ================
(epoch: 5) Overall_Acc: 0.987 Mean_IoU: 0.494 0: 0.987 1: 0.000 precision_1: 0.000 recall_1: 0.000 F1_1: 0.000 
================ val acc (Sun Jun 28 15:36:10 2020) ================
(epoch: 6) Overall_Acc: 0.990 Mean_IoU: 0.495 0: 0.990 1: 0.000 precision_1: 0.000 recall_1: 0.000 F1_1: 0.000 
================ val acc (Sun Jun 28 15:37:16 2020) ================
(epoch: 7) Overall_Acc: 0.970 Mean_IoU: 0.485 0: 0.970 1: 0.000 precision_1: 0.000 recall_1: 0.000 F1_1: 0.000 
================ val acc (Sun Jun 28 15:38:19 2020) ================
(epoch: 8) Overall_Acc: 0.986 Mean_IoU: 0.493 0: 0.986 1: 0.000 precision_1: 0.000 recall_1: 0.000 F1_1: 0.000 
================ val acc (Sun Jun 28 15:39:24 2020) ================
(epoch: 9) Overall_Acc: 0.978 Mean_IoU: 0.489 0: 0.978 1: 0.000 precision_1: 0.000 recall_1: 0.000 F1_1: 0.000 

my gt mask is binary image, 0 or 1.

**Comment by justchenhao** [comment]
I am not sure about that. Maybe it is due to the label. Have your label is 255/0 to denote the change/unchanged category?

**Comment by justchenhao** [comment]
Close for now. Feel free to reopen if you still have questions.
