### ISSUE TITLE
Test without label 

### ISSUE THREAD

**Issue by franjamonga** [justchenhao/STANet#17]
Hello, I would like to know how it would be possible to test without the label layer, that is, only the image from before and the image from after.

I imagine the code could be modified to do this.  
Thank you very much for your attention .  I await your response .

**Comment by raminrahimi6970** [comment]
Hi you just modify the val.py....
![image](https://user-images.githubusercontent.com/29606778/86201967-394b6980-bb76-11ea-9049-2ea748b219ea.png)

**Comment by justchenhao** [comment]
Close for now. I think the issue has been addressed.
