### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by PoonamZ** [justchenhao/STANet#2]
@justchenhao Are you planning to release pretrained weights?

**Comment by justchenhao** [comment]
Thanks for your attention, we have no plans to release pre-trained models.

**Comment by justchenhao** [comment]
You could find the PAM pre-trained model.

**Comment by mbenencase** [comment]
@justchenhao sorry to bother you, but is it possible for you to upload the pre-trained model in Google Drive? I can't download it

**Comment by ipScore** [comment]
@justchenhao when testing with the pre_trained weight, I got the metrics as the following:
`Overall_Acc: 0.987 Mean_IoU: 0.887 0: 0.987 1: 0.787 precision_1: 0.850 recall_1: 0.914 F1_1: 0.881 `

As for the `F1` score, it increases by `0.8% `compared with the results reported in the paper. 
I wonder if there any difference with the original PAM？Or just the different env.

**Comment by justchenhao** [comment]
@ipScore Thank you for your attention. It is true that the provided PAM model is a little different from that in the paper. We lost our original pre-train models for some reason. You could train yourself for a similar result.

**Comment by justchenhao** [comment]
Close for now. Feel free to reopen if you still have questions.

**Comment by HyunjiEllenPak** [comment]
> sorry to bother you, but is it possible for you to upload the pre-trained model in Google Drive? I can't download it


@mbenencase @justchenhao 

Hi, I am interested in your STANet. 
But I am struggling to download the pretrained weight from baido. Could you give me the google drive link? where is it?

**Comment by mbenencase** [comment]
Hello @HyunjiEllenPak , sorry for my late reply. I still have the pre-trained weights, I've uploaded them. Please, check the following link: https://drive.google.com/drive/folders/1OnLOV7Mv3vRi7cDI1_aYaisj3lvprM27?usp=sharing

If you cannot access the link please send me an e-mail to marcelo.benencase@unesp.br

I hope that it can help you!
