### ISSUE TITLE
python val.py, Error:No such file or directory: './xxxxxx_net_A.pth'

### ISSUE THREAD

**Issue by zsc1104** [justchenhao/STANet#20]
Hi, When I run python val.py, Error:No such file or directory: './xxxxxx_net_A.pth'. In the dir `LEVIR-CDF0`, only have 'xxx_net_F.pth'files, Where is the file of 'xxxxxx_net_A.pth'?
I'm sorry to interrupt, Thank you very much !!!

**Comment by zsc1104** [comment]
ok, It works, something need to modify in opts

**Comment by GusRoth** [comment]
> ok, It works, something need to modify in opts

what need to modify?
