### ISSUE TITLE
Hi,my BASE results is better than PAM.

### ISSUE THREAD

**Issue by louxiantuo** [justchenhao/STANet#22]
BASE:
(epoch: 196) Overall_Acc: 0.973 Mean_IoU: 0.787 0: 0.972 1: 0.602 precision_1: 0.612 recall_1: 0.972 F1_1: 0.751 
================ val acc (Tue Jul 21 23:39:54 2020) ================
(epoch: 197) Overall_Acc: 0.972 Mean_IoU: 0.784 0: 0.971 1: 0.596 precision_1: 0.607 recall_1: 0.971 F1_1: 0.747 
================ val acc (Tue Jul 21 23:40:53 2020) ================
(epoch: 198) Overall_Acc: 0.973 Mean_IoU: 0.786 0: 0.972 1: 0.600 precision_1: 0.612 recall_1: 0.970 F1_1: 0.750 
================ val acc (Tue Jul 21 23:41:53 2020) ================
(epoch: 199) Overall_Acc: 0.968 Mean_IoU: 0.766 0: 0.967 1: 0.565 precision_1: 0.572 recall_1: 0.977 F1_1: 0.722 
================ val acc (Tue Jul 21 23:42:53 2020) ================
(epoch: 200) Overall_Acc: 0.970 Mean_IoU: 0.773 0: 0.969 1: 0.577 precision_1: 0.585 recall_1: 0.974 F1_1: 0.731 

PAM:

================ val acc (Sun Jul 19 21:39:19 2020) ================
(epoch: 196) Overall_Acc: 0.976 Mean_IoU: 0.532 0: 0.976 1: 0.087 precision_1: 0.466 recall_1: 0.097 F1_1: 0.161 
================ val acc (Sun Jul 19 21:39:40 2020) ================
(epoch: 197) Overall_Acc: 0.976 Mean_IoU: 0.534 0: 0.976 1: 0.092 precision_1: 0.443 recall_1: 0.104 F1_1: 0.168 
================ val acc (Sun Jul 19 21:40:01 2020) ================
(epoch: 198) Overall_Acc: 0.976 Mean_IoU: 0.528 0: 0.976 1: 0.079 precision_1: 0.502 recall_1: 0.086 F1_1: 0.147 
================ val acc (Sun Jul 19 21:40:23 2020) ================
(epoch: 199) Overall_Acc: 0.976 Mean_IoU: 0.535 0: 0.975 1: 0.095 precision_1: 0.424 recall_1: 0.109 F1_1: 0.174 
================ val acc (Sun Jul 19 21:40:45 2020) ================
(epoch: 200) Overall_Acc: 0.976 Mean_IoU: 0.529 0: 0.976 1: 0.081 precision_1: 0.476 recall_1: 0.089 F1_1: 0.150

**Comment by GusRoth** [comment]
> BASE:
> (epoch: 196) Overall_Acc: 0.973 Mean_IoU: 0.787 0: 0.972 1: 0.602 precision_1: 0.612 recall_1: 0.972 F1_1: 0.751
> ================ val acc (Tue Jul 21 23:39:54 2020) ================
> (epoch: 197) Overall_Acc: 0.972 Mean_IoU: 0.784 0: 0.971 1: 0.596 precision_1: 0.607 recall_1: 0.971 F1_1: 0.747
> ================ val acc (Tue Jul 21 23:40:53 2020) ================
> (epoch: 198) Overall_Acc: 0.973 Mean_IoU: 0.786 0: 0.972 1: 0.600 precision_1: 0.612 recall_1: 0.970 F1_1: 0.750
> ================ val acc (Tue Jul 21 23:41:53 2020) ================
> (epoch: 199) Overall_Acc: 0.968 Mean_IoU: 0.766 0: 0.967 1: 0.565 precision_1: 0.572 recall_1: 0.977 F1_1: 0.722
> ================ val acc (Tue Jul 21 23:42:53 2020) ================
> (epoch: 200) Overall_Acc: 0.970 Mean_IoU: 0.773 0: 0.969 1: 0.577 precision_1: 0.585 recall_1: 0.974 F1_1: 0.731
> 
> PAM:
> 
> ================ val acc (Sun Jul 19 21:39:19 2020) ================
> (epoch: 196) Overall_Acc: 0.976 Mean_IoU: 0.532 0: 0.976 1: 0.087 precision_1: 0.466 recall_1: 0.097 F1_1: 0.161
> ================ val acc (Sun Jul 19 21:39:40 2020) ================
> (epoch: 197) Overall_Acc: 0.976 Mean_IoU: 0.534 0: 0.976 1: 0.092 precision_1: 0.443 recall_1: 0.104 F1_1: 0.168
> ================ val acc (Sun Jul 19 21:40:01 2020) ================
> (epoch: 198) Overall_Acc: 0.976 Mean_IoU: 0.528 0: 0.976 1: 0.079 precision_1: 0.502 recall_1: 0.086 F1_1: 0.147
> ================ val acc (Sun Jul 19 21:40:23 2020) ================
> (epoch: 199) Overall_Acc: 0.976 Mean_IoU: 0.535 0: 0.975 1: 0.095 precision_1: 0.424 recall_1: 0.109 F1_1: 0.174
> ================ val acc (Sun Jul 19 21:40:45 2020) ================
> (epoch: 200) Overall_Acc: 0.976 Mean_IoU: 0.529 0: 0.976 1: 0.081 precision_1: 0.476 recall_1: 0.089 F1_1: 0.150

Have you tested the ‘test’ result? If the test result get the same?

**Comment by louxiantuo** [comment]
No, I did not do the test, but I wonder why this is the case. PAM has not a good result.

**Comment by justchenhao** [comment]
Maybe close for now.
