### ISSUE TITLE
implementation detail about SZRAKI dataset

### ISSUE THREAD

**Issue by yoyoyoohh** [justchenhao/STANet#27]
Hi, in section 2.3 ( Implementation Details) of your paper, It said that when training on the SZTAKI dataset, the patch size is set to 784x448, which changes to 113x113 in the testing phase, however. But how can we adopt different sizes of images during training and testing?

**Comment by justchenhao** [comment]
Thanks for your attention. We follow the implementation in "Triplet-based semantic relation learning for aerial remote sensing image change detection". Patch size is 113 * 113 in the training phase, and patch size is 784 * 448 in the testing phase.
