### ISSUE TITLE
训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存

### ISSUE THREAD

**Issue by panghongwei17** [justchenhao/STANet#28]
请问如何解决呢，谢谢

**Comment by wangshihuang** [comment]
你看看测试图片大小，只能是256x256，原因不知

**Comment by panghongwei17** [comment]
能加个微信吗，朋友，最近搞了两天了，一直显存异常，谢谢了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 下午5:54
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"779415772"<779415772@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
你看看测试图片大小，只能是256x256，原因不知

**Comment by wangshihuang** [comment]
他提供的数据源是1024x1024，你切成256x256就行了

**Comment by panghongwei17** [comment]
好的，谢谢！
&nbsp;多谢指点！
我试一下。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 下午5:58
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"779415772"<779415772@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
他提供的数据源是1024x1024，你切成256x256就行了

**Comment by wangshihuang** [comment]
训练有precessing=resize_and_crop，所以是256x256，测试没有变化，还是1024x1024

**Comment by panghongwei17** [comment]
是的，训练代码中，在进行val（）时，显存异常，因此dataset val目录也需要resize到256*256吧？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上6:02
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"779415772"<779415772@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
训练有precessing=resize_and_crop，所以是256x256，测试没有变化，还是1024x1024

**Comment by wangshihuang** [comment]
测试一般不做变化，resize也可以，或者切图

**Comment by panghongwei17** [comment]
&nbsp;那现在也就是我只需要将val目录下的图片resize到256*256吗？然后正常调用val函数就行。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上6:09
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"779415772"<779415772@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
测试一般不做变化，resize也可以，或者切图

**Comment by wangshihuang** [comment]
可以，resize会有损失，建议切图

**Comment by panghongwei17** [comment]
您好，我这里参数设置的是256，不过还是爆显存不够，另外 base_options.py 中的--gpu_ids 参数设为0，1,2，3 并不能使用多卡训练，只能使用0卡进行训练。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上6:13
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"779415772"<779415772@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
可以，resize会有损失，建议切图

**Comment by panghongwei17** [comment]
另外，您说的切图是如何切呢，是给出的代码本身就有crops操作还是在val数据集中进行切图？ 有点懵


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上6:13
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"779415772"<779415772@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
可以，resize会有损失，建议切图

**Comment by panghongwei17** [comment]
我训练BAM、PAM模型都爆出了显存不够，而base模型可以进行正常训练和测试。而其他两个模型batch size都设置为1了，还需要64G的显存




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上6:13
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"779415772"<779415772@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
可以，resize会有损失，建议切图

**Comment by panghongwei17** [comment]
多谢，已经可以正常训练和测试。原始图像1024*1024 的确是这个问题。再次感谢！




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上6:13
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"779415772"<779415772@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
可以，resize会有损失，建议切图

**Comment by MaxwellJoker** [comment]
遇到了同样的问题，求解决方法

**Comment by MaxwellJoker** [comment]
遇到了同样的问题，在测试的时候显存要求64G，求解决方案

**Comment by panghongwei17** [comment]
最简单方法就是resize数据集到256*256





------------------ 原始邮件 ------------------
发件人: MaxwellJoker <notifications@github.com&gt;
发送时间: 2020年8月26日 15:52
收件人: justchenhao/STANet <STANet@noreply.github.com&gt;
抄送: panghongwei17 <779415772@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
遇到了同样的问题，在测试的时候显存要求64G，求解决方案

**Comment by MaxwellJoker** [comment]
训练BMP的时候 数据集resize到256*256后 迭代第二次还是会显存超出

**Comment by MaxwellJoker** [comment]
您好 resize后的数据集进行训练得到的F1非常低 0.15左右 这个您遇到过吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 晚上6:36
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"心 跳√ "<1072843554@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 最简单方法就是resize数据集到256*256 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: MaxwellJoker <notifications@github.com&amp;gt; 
 发送时间: 2020年8月26日 15:52 
 收件人: justchenhao/STANet <STANet@noreply.github.com&amp;gt; 
 抄送: panghongwei17 <779415772@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28) 
 
 
 
 
 
   
 遇到了同样的问题，在测试的时候显存要求64G，求解决方案

**Comment by panghongwei17** [comment]
对对 差不多就这个数 很奇怪





------------------ 原始邮件 ------------------
发件人: MaxwellJoker <notifications@github.com&gt;
发送时间: 2020年9月4日 23:56
收件人: justchenhao/STANet <STANet@noreply.github.com&gt;
抄送: panghongwei17 <779415772@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 您好 resize后的数据集进行训练得到的F1非常低 0.15左右 这个您遇到过吗？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年8月26日(星期三) 晚上6:36 
 收件人:&amp;nbsp;"justchenhao/STANet"<STANet@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"心 跳√ "<1072843554@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28) 
 
 
 
 
 
  最简单方法就是resize数据集到256*256  
   
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: MaxwellJoker <notifications@github.com&amp;amp;gt;  
  发送时间: 2020年8月26日 15:52  
  收件人: justchenhao/STANet <STANet@noreply.github.com&amp;amp;gt;  
  抄送: panghongwei17 <779415772@qq.com&amp;amp;gt;, Author <author@noreply.github.com&amp;amp;gt;  
  主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)  
   
   
   
   
   
     
  遇到了同样的问题，在测试的时候显存要求64G，求解决方案

**Comment by MaxwellJoker** [comment]
那您用crop成功了吗？得到的结果怎么样呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月5日(星期六) 凌晨0:01
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"心 跳√ "<1072843554@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 对对 差不多就这个数 很奇怪 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: MaxwellJoker <notifications@github.com&amp;gt; 
 发送时间: 2020年9月4日 23:56 
 收件人: justchenhao/STANet <STANet@noreply.github.com&amp;gt; 
 抄送: panghongwei17 <779415772@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28) 
 
 
 
 
 
  您好 resize后的数据集进行训练得到的F1非常低 0.15左右 这个您遇到过吗？  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年8月26日(星期三) 晚上6:36  
  收件人:&amp;amp;nbsp;"justchenhao/STANet"<STANet@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"心 跳√ "<1072843554@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)  
   
   
   
   
   
   最简单方法就是resize数据集到256*256   
     
     
     
     
     
   ------------------ 原始邮件 ------------------   
   发件人: MaxwellJoker <notifications@github.com&amp;amp;amp;gt;   
   发送时间: 2020年8月26日 15:52   
   收件人: justchenhao/STANet <STANet@noreply.github.com&amp;amp;amp;gt;   
   抄送: panghongwei17 <779415772@qq.com&amp;amp;amp;gt;, Author <author@noreply.github.com&amp;amp;amp;gt;   
   主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)   
     
     
     
     
     
       
   遇到了同样的问题，在测试的时候显存要求64G，求解决方案

**Comment by panghongwei17** [comment]
我没有用crops 直接resize了，就是训练后感觉评价指标都很低





------------------ 原始邮件 ------------------
发件人: MaxwellJoker <notifications@github.com&gt;
发送时间: 2020年9月5日 00:03
收件人: justchenhao/STANet <STANet@noreply.github.com&gt;
抄送: panghongwei17 <779415772@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 那您用crop成功了吗？得到的结果怎么样呢 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月5日(星期六) 凌晨0:01 
 收件人:&amp;nbsp;"justchenhao/STANet"<STANet@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"心 跳√ "<1072843554@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28) 
 
 
 
 
 
  对对 差不多就这个数 很奇怪  
   
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: MaxwellJoker <notifications@github.com&amp;amp;gt;  
  发送时间: 2020年9月4日 23:56  
  收件人: justchenhao/STANet <STANet@noreply.github.com&amp;amp;gt;  
  抄送: panghongwei17 <779415772@qq.com&amp;amp;gt;, Author <author@noreply.github.com&amp;amp;gt;  
  主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)  
   
   
   
   
   
   您好 resize后的数据集进行训练得到的F1非常低 0.15左右 这个您遇到过吗？   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年8月26日(星期三) 晚上6:36   
   收件人:&amp;amp;amp;nbsp;"justchenhao/STANet"<STANet@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"心 跳√ "<1072843554@qq.com&amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)   
     
     
     
     
     
    最简单方法就是resize数据集到256*256    
       
       
       
       
       
    ------------------ 原始邮件 ------------------    
    发件人: MaxwellJoker <notifications@github.com&amp;amp;amp;amp;gt;    
    发送时间: 2020年8月26日 15:52    
    收件人: justchenhao/STANet <STANet@noreply.github.com&amp;amp;amp;amp;gt;    
    抄送: panghongwei17 <779415772@qq.com&amp;amp;amp;amp;gt;, Author <author@noreply.github.com&amp;amp;amp;amp;gt;    
    主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)    
       
       
       
       
       
         
    遇到了同样的问题，在测试的时候显存要求64G，求解决方案

**Comment by MaxwellJoker** [comment]
那您测试的时候呢？resize了吗？我不进行resize 的话还是会cuda out of memory，需要64G内存

**Comment by panghongwei17** [comment]
测试也resize了 对的 要不然就爆了





------------------ 原始邮件 ------------------
发件人: MaxwellJoker <notifications@github.com&gt;
发送时间: 2020年9月5日 00:08
收件人: justchenhao/STANet <STANet@noreply.github.com&gt;
抄送: panghongwei17 <779415772@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
那您测试的时候呢？resize了吗？我不进行resize 的话还是会cuda out of memory，需要64G内存

**Comment by MaxwellJoker** [comment]
可以给个微信吗？

**Comment by panghongwei17** [comment]
可以呀





------------------ 原始邮件 ------------------
发件人: MaxwellJoker <notifications@github.com&gt;
发送时间: 2020年9月5日 00:16
收件人: justchenhao/STANet <STANet@noreply.github.com&gt;
抄送: panghongwei17 <779415772@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
可以给个微信吗？

**Comment by liudong315** [comment]
我在训练时候需要一些问题，请问能不能帮忙解决下。
![image](https://user-images.githubusercontent.com/33924595/92734441-2097d500-f3ab-11ea-950f-8150c4e35338.png)

**Comment by MaxwellJoker** [comment]
这是visdom版本的问题，在已经close的问题里有解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月10日(星期四) 晚上9:18
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"心 跳√ "<1072843554@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
我在训练时候需要一些问题，请问能不能帮忙解决下。

**Comment by liudong315** [comment]
我没找到诶，可以麻烦你给个链接或者截个图给我看下吗，谢谢！

**Comment by MaxwellJoker** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月10日(星期四) 晚上9:25
收件人:&nbsp;"justchenhao/STANet"<STANet@noreply.github.com&gt;;
抄送:&nbsp;"心 跳√ "<1072843554@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28)





 
我没找到诶，可以麻烦你给个链接或者截个图给我看下吗，谢谢！

**Comment by liudong315** [comment]
您好，请问在Val()中显存爆炸应该怎么解决，如何处理val中的图片为256，有代码吗，谢谢！
![image](https://user-images.githubusercontent.com/33924595/95642971-adcf6600-0ade-11eb-818c-848600ebc1ec.png)

**Comment by liudong315** [comment]
> 可以呀
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: MaxwellJoker <notifications@github.com&gt; 发送时间: 2020年9月5日 00:16 收件人: justchenhao/STANet <STANet@noreply.github.com&gt; 抄送: panghongwei17 <779415772@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28) 可以给个微信吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，可以加个微信吗，代码遇到了问题难以解决。

**Comment by xixi103** [comment]
切图之后，python train.py出现下面错误，不知道是什么原因
> `Traceback (most recent call last):
  File "train.py", line 127, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/home/user/zxm/stanet/STANet-master/STANet-master/data/__init__.py", line 80, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2515, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 3), '<f8')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/zxm/stanet/STANet-master/STANet-master/data/changedetection_dataset.py", line 51, in __getitem__
    L_img = Image.fromarray(tmp)
  File "/home/user/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2517, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type`

**Comment by DLT10010** [comment]
> 我没找到诶，可以麻烦你给个链接或者截个图给我看下吗，谢谢！

怎么解决 呢，我也遇到了相同问题。安装的是什么版本的啊，能解答一下吗，谢谢（How to solve it? I have the same problem. What version is installed ah, can answer, thank you）

**Comment by liudong315** [comment]
> > 我没找到诶，可以麻烦你给个链接或截个图给我看下吗，谢谢！
> 
> 怎么解决呢呢，我也遇到了相同的问题。安装的是什么版本的啊，能解答一下吗，谢谢（如何解决？我也有同样的问题。什么版本的安装啊，可以回答，谢谢）

这是visdom版本的问题。您可以将其版本更改为0.1.8.1，然后才能正常运行

**Comment by DLT10010** [comment]
> 可以呀
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: MaxwellJoker <notifications@github.com&gt; 发送时间: 2020年9月5日 00:16 收件人: justchenhao/STANet <STANet@noreply.github.com&gt; 抄送: panghongwei17 <779415772@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[justchenhao/STANet] 训练PAM模型 batchsize设置为1，在进行val（）时 需要64G显存 (#28) 可以给个微信吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，能给个微信吗，我也是内存不足问题，怎么将测试图片切成256*256的啊。劳烦您了。

**Comment by DLT10010** [comment]
> 请问如何解决呢，谢谢

请问一下除了把测试图片大小改为256x256之外还有什么办法吗，谢谢
