### ISSUE TITLE
image size in the testing phase

### ISSUE THREAD

**Issue by ipScore** [justchenhao/STANet#3]
Hey, BUAAer@justchenhao 

Great works! Thanks for sharing the LEVIR-CD dataset.

I wonder if all the results on the LEVIR-CD data(i.e` Table 4 and Table 5` in the paper) are obtained from` testing directly with input size 1024x1024`? Or on `256x256` patches and then stitch these patches into a full size image?

And would you like to build `a public leadbord` with this dataset for `Building Change Detection from Remote Sensing Images`? e.g. on `https://paperswithcode.com/`?

**Comment by justchenhao** [comment]
Greeting！Thank you for your attention. In our paper, all the results on the LEVIR-CD data are obtained on 256 * 256 patches. (Note that better results may be achieved when directly using images size of 1024*1024. We consider that when testing PAM with full-size images, the memory consumption limit will be exceeded.)
Thank you for your kind suggestion. We would like to build a leaderboard on paperwithcode.

**Comment by ipScore** [comment]
@justchenhao awaiting.
