### ISSUE TITLE
请问每次训练进行测试，结果得到的metrics肯定是有差异的，请问在文章中您是取几次实验最好？还是取几次实验的平均作为结果放进论文中呢？

### ISSUE THREAD

**Issue by GusRoth** [justchenhao/STANet#33]
希望可以得到您的指点！谢谢！

**Comment by GusRoth** [comment]
我指的是test的结果！

**Comment by justchenhao** [comment]
您好，感谢您的关注。在模型训练阶段中，每训练一轮，会在验证集上计算准确率，最终保留在验证集上最好的结果，用于在测试集上测试。

**Comment by GusRoth** [comment]
> 您好，感谢您的关注。在模型训练阶段中，每训练一轮，会在验证集上计算准确率，最终保留在验证集上最好的结果，用于在测试集上测试。

感谢您的回复！但是我想询问的并非是这个流程。想问的是您每次跑整个训练流程都能够得到每次的验证集上最好的模型，此时多次实验得到的几个验证集最好模型，都在测试集上测试应当会得到不同的结果，所以您的意思是多次实验取其中最好的结果还是平均结果放进论文里面的？

**Comment by justchenhao** [comment]
是取的平均结果哈

**Comment by weizhiliang0520** [comment]
> 

您好，我尝试利用您的代码运行代码，在准备数据之后
训练模型（python train.py）
但是报错如下，请问如何解决？

`create web directory ./checkpoints/LEVIR-CDF0/web...
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
(epoch: 1, iters: 100, time: 0.148, data: 1.769) f: 87.757 
(epoch: 1, iters: 200, time: 0.130, data: 0.137) f: 115.569 
(epoch: 1, iters: 300, time: 0.148, data: 0.010) f: 96.835 
(epoch: 1, iters: 400, time: 0.124, data: 0.006) f: 109.782 
(epoch: 1) current_t_epoch: 82.002 
saving the model at the end of epoch 1, iters 444
changedetection
['./LEVIR-CD/val/A/val_1.png', './LEVIR-CD/val/A/val_10.png', './LEVIR-CD/val/A/val_11.png', './LEVIR-CD/val/A/val_12.png', './LEVIR-CD/val/A/val_13.png', './LEVIR-CD/val/A/val_14.png', './LEVIR-CD/val/A/val_15.png', './LEVIR-CD/val/A/val_16.png', './LEVIR-CD/val/A/val_17.png', './LEVIR-CD/val/A/val_18.png', './LEVIR-CD/val/A/val_19.png', './LEVIR-CD/val/A/val_2.png', './LEVIR-CD/val/A/val_20.png', './LEVIR-CD/val/A/val_21.png', './LEVIR-CD/val/A/val_22.png', './LEVIR-CD/val/A/val_23.png', './LEVIR-CD/val/A/val_24.png', './LEVIR-CD/val/A/val_25.png', './LEVIR-CD/val/A/val_26.png', './LEVIR-CD/val/A/val_27.png', './LEVIR-CD/val/A/val_28.png', './LEVIR-CD/val/A/val_29.png', './LEVIR-CD/val/A/val_3.png', './LEVIR-CD/val/A/val_30.png', './LEVIR-CD/val/A/val_31.png', './LEVIR-CD/val/A/val_32.png', './LEVIR-CD/val/A/val_33.png', './LEVIR-CD/val/A/val_34.png', './LEVIR-CD/val/A/val_35.png', './LEVIR-CD/val/A/val_36.png', './LEVIR-CD/val/A/val_37.png', './LEVIR-CD/val/A/val_38.png', './LEVIR-CD/val/A/val_39.png', './LEVIR-CD/val/A/val_4.png', './LEVIR-CD/val/A/val_40.png', './LEVIR-CD/val/A/val_41.png', './LEVIR-CD/val/A/val_42.png', './LEVIR-CD/val/A/val_43.png', './LEVIR-CD/val/A/val_44.png', './LEVIR-CD/val/A/val_45.png', './LEVIR-CD/val/A/val_46.png', './LEVIR-CD/val/A/val_47.png', './LEVIR-CD/val/A/val_48.png', './LEVIR-CD/val/A/val_49.png', './LEVIR-CD/val/A/val_5.png', './LEVIR-CD/val/A/val_50.png', './LEVIR-CD/val/A/val_51.png', './LEVIR-CD/val/A/val_52.png', './LEVIR-CD/val/A/val_53.png', './LEVIR-CD/val/A/val_54.png', './LEVIR-CD/val/A/val_55.png', './LEVIR-CD/val/A/val_56.png', './LEVIR-CD/val/A/val_57.png', './LEVIR-CD/val/A/val_58.png', './LEVIR-CD/val/A/val_59.png', './LEVIR-CD/val/A/val_6.png', './LEVIR-CD/val/A/val_60.png', './LEVIR-CD/val/A/val_61.png', './LEVIR-CD/val/A/val_62.png', './LEVIR-CD/val/A/val_63.png', './LEVIR-CD/val/A/val_64.png', './LEVIR-CD/val/A/val_7.png', './LEVIR-CD/val/A/val_8.png', './LEVIR-CD/val/A/val_9.png']
dataset [ChangeDetectionDataset] was created
tcmalloc: large alloc 2147483648 bytes == 0x55695f70e000 @  0x7f3d0a0c9b6b 0x7f3d0a0e9379 0x7f3c098cecde 0x7f3c098d0452 0x7f3c5b8f7cf3 0x7f3c5b97f158 0x7f3c5c05649f 0x7f3c5c036870 0x7f3c5be2148a 0x7f3c5b97029d 0x7f3c5c14faca 0x7f3c5c03270e 0x7f3c5bbf7d17 0x7f3c5d55a7c4 0x7f3c5d55ac8d 0x7f3c5bc6d6e8 0x7f3c5b96e3d5 0x7f3c5c1d6970 0x7f3c5bf23069 0x7f3d04d2f2c3 0x7f3d04e8904e 0x5568f52e94b0 0x5568f53dae1d 0x5568f535ce99 0x5568f53579ee 0x5568f52eabda 0x5568f5359737 0x5568f52eaafa 0x5568f5358915 0x5568f53579ee 0x5568f53576f3
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    miou_current = val(opt, model)
  File "train.py", line 86, in val
    score = model.test(val=True)           # run inference
  File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/models/CDF0_model.py", line 79, in test
    metrics.update(self.L.detach().cpu().numpy(), pred.detach().cpu().numpy())
  File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/util/metrics.py", line 121, in update
    self.confusion_matrix += self.__fast_hist(lt.flatten(), lp.flatten())
  File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/util/metrics.py", line 108, in __fast_hist
    hist = np.bincount(self.num_classes * label_gt[mask].astype(int) + label_pred[mask],
IndexError: boolean index did not match indexed array along dimension 0; dimension is 67108864 but corresponding boolean dimension is 1048576`

**Comment by weizhiliang0520** [comment]
> 您好，感谢您的关注。在模型训练阶段中，每训练一轮，会在验证集上计算准确率，最终保留在验证集上最好的结果，用于在测试集上测试。

您好，在运行训练py文件之后，出现以下的错误，请问如何解决呢？

`create web directory ./checkpoints/LEVIR-CDF0/web... /usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary. cpuset_checked)) 
(epoch: 1, iters: 100, time: 0.148, data: 1.769) f: 87.757 
(epoch: 1, iters: 200, time: 0.130, data: 0.137) f: 115.569 
(epoch: 1, iters: 300, time: 0.148, data: 0.010) f: 96.835 
(epoch: 1, iters: 400, time: 0.124, data: 0.006) f: 109.782 
(epoch: 1) current_t_epoch: 82.002 

saving the model at the end of epoch 1, iters 444 changedetection ['./LEVIR-CD/val/A/val_1.png', './LEVIR-CD/val/A/val_10.png', './LEVIR-CD/val/A/val_11.png', './LEVIR-CD/val/A/val_12.png', './LEVIR-CD/val/A/val_13.png', './LEVIR-CD/val/A/val_14.png', './LEVIR-CD/val/A/val_15.png', './LEVIR-CD/val/A/val_16.png', './LEVIR-CD/val/A/val_17.png', './LEVIR-CD/val/A/val_18.png', './LEVIR-CD/val/A/val_19.png', './LEVIR-CD/val/A/val_2.png', './LEVIR-CD/val/A/val_20.png', './LEVIR-CD/val/A/val_21.png', './LEVIR-CD/val/A/val_22.png', './LEVIR-CD/val/A/val_23.png', './LEVIR-CD/val/A/val_24.png', './LEVIR-CD/val/A/val_25.png', './LEVIR-CD/val/A/val_26.png', './LEVIR-CD/val/A/val_27.png', './LEVIR-CD/val/A/val_28.png', './LEVIR-CD/val/A/val_29.png', './LEVIR-CD/val/A/val_3.png', './LEVIR-CD/val/A/val_30.png', './LEVIR-CD/val/A/val_31.png', './LEVIR-CD/val/A/val_32.png', './LEVIR-CD/val/A/val_33.png', './LEVIR-CD/val/A/val_34.png', './LEVIR-CD/val/A/val_35.png', './LEVIR-CD/val/A/val_36.png', './LEVIR-CD/val/A/val_37.png', './LEVIR-CD/val/A/val_38.png', './LEVIR-CD/val/A/val_39.png', './LEVIR-CD/val/A/val_4.png', './LEVIR-CD/val/A/val_40.png', './LEVIR-CD/val/A/val_41.png', './LEVIR-CD/val/A/val_42.png', './LEVIR-CD/val/A/val_43.png', './LEVIR-CD/val/A/val_44.png', './LEVIR-CD/val/A/val_45.png', './LEVIR-CD/val/A/val_46.png', './LEVIR-CD/val/A/val_47.png', './LEVIR-CD/val/A/val_48.png', './LEVIR-CD/val/A/val_49.png', './LEVIR-CD/val/A/val_5.png', './LEVIR-CD/val/A/val_50.png', './LEVIR-CD/val/A/val_51.png', './LEVIR-CD/val/A/val_52.png', './LEVIR-CD/val/A/val_53.png', './LEVIR-CD/val/A/val_54.png', './LEVIR-CD/val/A/val_55.png', './LEVIR-CD/val/A/val_56.png', './LEVIR-CD/val/A/val_57.png', './LEVIR-CD/val/A/val_58.png', './LEVIR-CD/val/A/val_59.png', './LEVIR-CD/val/A/val_6.png', './LEVIR-CD/val/A/val_60.png', './LEVIR-CD/val/A/val_61.png', './LEVIR-CD/val/A/val_62.png', './LEVIR-CD/val/A/val_63.png', './LEVIR-CD/val/A/val_64.png', './LEVIR-CD/val/A/val_7.png', './LEVIR-CD/val/A/val_8.png', './LEVIR-CD/val/A/val_9.png'] dataset [ChangeDetectionDataset] was created tcmalloc: large alloc 2147483648 bytes == 0x55695f70e000 @ 0x7f3d0a0c9b6b 0x7f3d0a0e9379 0x7f3c098cecde 0x7f3c098d0452 0x7f3c5b8f7cf3 0x7f3c5b97f158 0x7f3c5c05649f 0x7f3c5c036870 0x7f3c5be2148a 0x7f3c5b97029d 0x7f3c5c14faca 0x7f3c5c03270e 0x7f3c5bbf7d17 0x7f3c5d55a7c4 0x7f3c5d55ac8d 0x7f3c5bc6d6e8 0x7f3c5b96e3d5 0x7f3c5c1d6970 0x7f3c5bf23069 0x7f3d04d2f2c3 0x7f3d04e8904e 0x5568f52e94b0 0x5568f53dae1d 0x5568f535ce99 0x5568f53579ee 0x5568f52eabda 0x5568f5359737 0x5568f52eaafa 0x5568f5358915 0x5568f53579ee 0x5568f53576f3 Traceback (most recent call last): File "train.py", line 169, in <module> miou_current = val(opt, model) File "train.py", line 86, in val score = model.test(val=True) # run inference File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/models/CDF0_model.py", line 79, in test metrics.update(self.L.detach().cpu().numpy(), pred.detach().cpu().numpy()) File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/util/metrics.py", line 121, in update self.confusion_matrix += self.__fast_hist(lt.flatten(), lp.flatten()) File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/util/metrics.py", line 108, in __fast_hist hist = np.bincount(self.num_classes * label_gt[mask].astype(int) + label_pred[mask], IndexError: boolean index did not match indexed array along dimension 0; dimension is 67108864 but corresponding boolean dimension is 1048576`

**Comment by ABCD121-SOURCE** [comment]
> 

你好，我和你遇到了同样的问题，请问你是怎样解决的呢？

**Comment by ABCD121-SOURCE** [comment]
>
