### ISSUE TITLE
关于预训练模型的问题

### ISSUE THREAD

**Issue by beifangbai** [justchenhao/STANet#37]
我使用了您提供的Pre-train Module，进行测试，测试结果F1为0.881，而论文中F1为87.3。请问您是取了多次的平均值吗？

**Comment by justchenhao** [comment]
感谢您的关注哈。是做了多次平均值。

**Comment by samanthawyf** [comment]
您好，目前我看到分享工程里没有pere-train model，可以共享一下吗? @justchenhao @beifangbai
