### ISSUE TITLE
Precision recall computation.

### ISSUE THREAD

**Issue by divyanshj16** [justchenhao/STANet#38]
Hi,
I have my own implementation of precision and recall which is giving precision f1 score of 0.3 while the implementation in this repo is giving a f1 score of 0.8.
I saw that the score is implemented in a very unfamiliar way?
Could you check if your implementation is correct?

**Comment by justchenhao** [comment]
Thanks for your attention. I am sure that our implementation is correct. You could write your implementation here, and we can have a discussion.

**Comment by justchenhao** [comment]
Close for now. Welcome to re-issue.
