### ISSUE TITLE
about label

### ISSUE THREAD

**Issue by francislinker** [justchenhao/STANet#4]
learned a lot from you, thanks. one more question. how can I label my own image dataset just like LEVIR-CD, is there any tools or code?

**Comment by justchenhao** [comment]
Thank you for your attention. We would like to suggest you use PhotoShop to manually label your own dataset.

**Comment by ipScore** [comment]
Hey, @francislinker , 
`ENVI 5.5` (`http://blog.sina.com.cn/s/blog_764b1e9d0102ycm2.html`) is also recommended.

**Comment by wangshihuang** [comment]
HI! 同样的代码，把256x256的数据换成512x512的数据，就报显存不足，换一台大显存机器还是一样，是要修改某处代码吗？

**Comment by swjtulinxi** [comment]
labelme is also recommended

**Comment by justchenhao** [comment]
close for now
