### ISSUE TITLE
图片分块之后训练BAM，评价指标是都很低，什么原因？

### ISSUE THREAD

**Issue by xixi103** [justchenhao/STANet#44]
`(epoch: 200) Overall_Acc: 0.223 Mean_IoU: 0.121 0: 0.188 1: 0.054 precision_1: 0.054 recall_1: 0.887 F1_1: 0.102 `

**Comment by liudong315** [comment]
请问如何对val中图片进行切片？

**Comment by justchenhao** [comment]
切片都正确嘛？
