### ISSUE TITLE
在BCDD数据集上不能收敛

### ISSUE THREAD

**Issue by sungh66** [justchenhao/STANet#62]
这篇论文Fully Convolutional Networks for Multisource Building Extraction From an Open Aerial and Satellite Imagery Data Set给出的数据集，使用你的BAM网络训练，完全不能收敛，数据集是切割成256x256的7k多张图片。期待您的回复

**Comment by sungh66** [comment]
由于裁剪的尺度128过小所以参数过于离散导致loss的波动太大，现在已解决，能在BCDD数据集F达到0.8

**Comment by AlongLove** [comment]
> 由于裁剪的尺度128过小所以参数过于离散导致loss的波动太大，现在已解决，能在BCDD数据集F达到0.8

请问您是怎么解决的呢？我在这论文的数据集上使用bam，裁剪成128的也不收敛，loss波动很大，最后也没趋于稳定
