### ISSUE TITLE
论文结果复现了

### ISSUE THREAD

**Issue by wgh0** [justchenhao/STANet#65]
![image](https://user-images.githubusercontent.com/48881536/115978423-d702a000-a5b1-11eb-9e7d-3680b4278cd4.png)
论文结果复现了， 没什么问题

**Comment by AlongLove** [comment]
请问您遇到过CUDA out of memory的问题么？请问您是怎么解决的啊？

**Comment by wgh0** [comment]
有遇到过，最后把图像切成256x256输入，再训练就没这个问题了

**Comment by Canoeof** [comment]
> 请问您遇到过CUDA out of memory的问题么？请问您是怎么解决的啊？

裁剪图片，你也是本科生毕设吗？

**Comment by wgh0** [comment]
不是

**Comment by Canoeof** [comment]
> 不是

我的epoch保存从158直接就到latest了，请问你是怎么保存193epoch的

**Comment by GuitarZhang** [comment]
请问你用的命令是：python ./train.py --save_epoch_freq 1 --angle 15 --dataroot ~/LEVIR_CD/train_256/ --val_dataroot ~/LEVIR_CD/val_256/ --name LEVIR-CDFAp0 --lr 0.001 --model CDFA --SA_mode PAM --batch_size 8--load_size 256--crop_size 256 --preprocess rotate_and_crop 吗？
请问batch_size设的是多少？另外裁剪的时候重叠吗？
我裁成了256*256不重叠，网络resnet18，结果非常不好，f1才78左右。

**Comment by wgh0** [comment]
@GuitarZhang 
![image](https://user-images.githubusercontent.com/48881536/117523841-f6a3ba80-afec-11eb-972f-825ea737d22c.png)batch_size设

**Comment by lijiaxiaozi** [comment]
> ![image](https://user-images.githubusercontent.com/48881536/115978423-d702a000-a5b1-11eb-9e7d-3680b4278cd4.png)
> 论文结果复现了， 没什么问题

你好，裁剪256*256是在训练命令中那个crop_size吗？我的F1得分只有0.773，Precision只有0.649。

**Comment by wgh0** [comment]
@ 

> > ![image](https://user-images.githubusercontent.com/48881536/115978423-d702a000-a5b1-11eb-9e7d-3680b4278cd4.png)
> > 论文结果复现了， 没什么问题
> 
> 你好，裁剪256*256是在训练命令中那个crop_size吗？我的F1得分只有0.773，Precision只有0.6

**Comment by wgh0** [comment]
> @
> 
> > > ![image](https://user-images.githubusercontent.com/48881536/115978423-d702a000-a5b1-11eb-9e7d-3680b4278cd4.png)
> > > 论文结果复现了， 没什么问题
> > 
> > 
> > 你好，裁剪256*256是在训练命令中那个crop_size吗？我的F1得分只有0.773，Precision只有0.6

有设置crop_size 256 感觉不影响，默认就是256

**Comment by AlongLove** [comment]
> > > @GuitarZhang
> > > ![image](https://user-images.githubusercontent.com/48881536/117523841-f6a3ba80-afec-11eb-972f-825ea737d22c.png)batch_size设的是8，没有重叠，我之前也是0.78，把那个ds设置成1，就好的
> > 
> > 
> > ds默认的不就是1么？我crop_size和load_size设置为128能跑，PAM的F1是0.843，设置为256还是爆显存，我已经把图片都切成256x256的了，请问您还做了其他的更改么？
> 
> 并没有其他修改，可能是我显存比较大32G，你有这个数据集吗 https://tianchi.aliyun.com/competition/entrance/231615/information

没有，我用的他的LEVIR-CD的数据集

**Comment by Pythondog3** [comment]
> > @GuitarZhang
> > ![image](https://user-images.githubusercontent.com/48881536/117523841-f6a3ba80-afec-11eb-972f-825ea737d22c.png)batch_size设的是8，没有重叠，我之前也是0.78，把那个ds设置成1，就好的
> 
> ds默认的不就是1么？我crop_size和load_size设置为128能跑，PAM的F1是0.843，设置为256还是爆显存，我已经把图片都切成256x256的了，请问您还做了其他的更改么？

你好，你的显存是多大的，我的是8G，设置ds=1，crop_size和load_size为128显存就炸了

**Comment by swjtulinxi** [comment]
请问你是用默认学习率0.0002，还是0.001， 我换成0.001直接没法学习，梯度爆炸

**Comment by weizhiliang0520** [comment]
> ![image](https://user-images.githubusercontent.com/48881536/115978423-d702a000-a5b1-11eb-9e7d-3680b4278cd4.png) 论文结果复现了， 没什么问题
您好，我开始运行train.py之后，出现下面的错误，请问你知道如何解决吗？
Experiment/codes/33_STANet/STANet/models/CDF0_model.py", line 79, in test
    metrics.update(self.L.detach().cpu().numpy(), pred.detach().cpu().numpy())
  File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/util/metrics.py", line 121, in update
    self.confusion_matrix += self.__fast_hist(lt.flatten(), lp.flatten())
  File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/util/metrics.py", line 108, in __fast_hist
    hist = np.bincount(self.num_classes * label_gt[mask].astype(int) + label_pred[mask],
IndexError: boolean index did not match indexed array along dimension 0; dimension is 67108864 but corresponding boolean dimension is 1048576

**Comment by cloudandsun** [comment]
> 请问你是用默认学习率0.0002，还是0.001， 我换成0.001直接没法学习，梯度爆炸
学习率用的默认的

**Comment by cloudandsun** [comment]
> > ![image](https://user-images.githubusercontent.com/48881536/115978423-d702a000-a5b1-11eb-9e7d-3680b4278cd4.png) 论文结果复现了， 没什么问题
> > 您好，我开始运行train.py之后，出现下面的错误，请问你知道如何解决吗？
> > Experiment/codes/33_STANet/STANet/models/CDF0_model.py", line 79, in test
> > metrics.update(self.L.detach().cpu().numpy(), pred.detach().cpu().numpy())
> > File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/util/metrics.py", line 121, in update
> > self.confusion_matrix += self.__fast_hist(lt.flatten(), lp.flatten())
> > File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/util/metrics.py", line 108, in __fast_hist
> > hist = np.bincount(self.num_classes * label_gt[mask].astype(int) + label_pred[mask],
> > IndexError: boolean index did not match indexed array along dimension 0; dimension is 67108864 but corresponding boolean dimension is 1048576

不好意思，时间过去有点久，不是很清楚这个错误是否遇到过

**Comment by cloudandsun** [comment]
> > > @GuitarZhang
> > > ![image](https://user-images.githubusercontent.com/48881536/117523841-f6a3ba80-afec-11eb-972f-825ea737d22c.png)batch_size设的是8，没有重叠，我之前也是0.78，把那个ds设置成1，就好的
> > 
> > 
> > ds默认的不就是1么？我crop_size和load_size设置为128能跑，PAM的F1是0.843，设置为256还是爆显存，我已经把图片都切成256x256的了，请问您还做了其他的更改么？
> 
> 你好，你的显存是多大的，我的是8G，设置ds=1，crop_size和load_size为128显存就炸了

32G

**Comment by weizhiliang0520** [comment]
> > 请问你是用默认学习率0.0002，还是0.001， 我换成0.001直接没法学习，梯度爆炸
> > 学习率用的默认的

好的，我都是直接运行的，从报错过程来看，跑完第一个epoch以后，val 就报错了，如下：

`[Network F] Total number of parameters : 16.892 M
-----------------------------------------------

Could not connect to Visdom server. 
 Trying to start a server....
Command: /usr/bin/python3 -m visdom.server -p 8097 &>/dev/null &
create web directory ./checkpoints/LEVIR-CDF0/web...
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))

(epoch: 1, iters: 100, time: 0.085, data: 1.904) f: 45.299 
(epoch: 1, iters: 200, time: 0.065, data: 0.283) f: 34.767 
(epoch: 1, iters: 300, time: 0.086, data: 0.018) f: 148.914 
(epoch: 1, iters: 400, time: 0.095, data: 0.680) f: 132.547 
(epoch: 1) current_t_epoch: 76.626 
saving the model at the end of epoch 1, iters 444
changedetection
['./LEVIR-CD/val/A/val_1.png', './LEVIR-CD/val/A/val_10.png', './LEVIR-CD/val/A/val_11.png', './LEVIR-CD/val/A/val_12.png', './LEVIR-CD/val/A/val_13.png', './LEVIR-CD/val/A/val_14.png', './LEVIR-CD/val/A/val_15.png', './LEVIR-CD/val/A/val_16.png', './LEVIR-CD/val/A/val_17.png', './LEVIR-CD/val/A/val_18.png', './LEVIR-CD/val/A/val_19.png', './LEVIR-CD/val/A/val_2.png', './LEVIR-CD/val/A/val_20.png', './LEVIR-CD/val/A/val_21.png', './LEVIR-CD/val/A/val_22.png', './LEVIR-CD/val/A/val_23.png', './LEVIR-CD/val/A/val_24.png', './LEVIR-CD/val/A/val_25.png', './LEVIR-CD/val/A/val_26.png', './LEVIR-CD/val/A/val_27.png', './LEVIR-CD/val/A/val_28.png', './LEVIR-CD/val/A/val_29.png', './LEVIR-CD/val/A/val_3.png', './LEVIR-CD/val/A/val_30.png', './LEVIR-CD/val/A/val_31.png', './LEVIR-CD/val/A/val_32.png', './LEVIR-CD/val/A/val_33.png', './LEVIR-CD/val/A/val_34.png', './LEVIR-CD/val/A/val_35.png', './LEVIR-CD/val/A/val_36.png', './LEVIR-CD/val/A/val_37.png', './LEVIR-CD/val/A/val_38.png', './LEVIR-CD/val/A/val_39.png', './LEVIR-CD/val/A/val_4.png', './LEVIR-CD/val/A/val_40.png', './LEVIR-CD/val/A/val_41.png', './LEVIR-CD/val/A/val_42.png', './LEVIR-CD/val/A/val_43.png', './LEVIR-CD/val/A/val_44.png', './LEVIR-CD/val/A/val_45.png', './LEVIR-CD/val/A/val_46.png', './LEVIR-CD/val/A/val_47.png', './LEVIR-CD/val/A/val_48.png', './LEVIR-CD/val/A/val_49.png', './LEVIR-CD/val/A/val_5.png', './LEVIR-CD/val/A/val_50.png', './LEVIR-CD/val/A/val_51.png', './LEVIR-CD/val/A/val_52.png', './LEVIR-CD/val/A/val_53.png', './LEVIR-CD/val/A/val_54.png', './LEVIR-CD/val/A/val_55.png', './LEVIR-CD/val/A/val_56.png', './LEVIR-CD/val/A/val_57.png', './LEVIR-CD/val/A/val_58.png', './LEVIR-CD/val/A/val_59.png', './LEVIR-CD/val/A/val_6.png', './LEVIR-CD/val/A/val_60.png', './LEVIR-CD/val/A/val_61.png', './LEVIR-CD/val/A/val_62.png', './LEVIR-CD/val/A/val_63.png', './LEVIR-CD/val/A/val_64.png', './LEVIR-CD/val/A/val_7.png', './LEVIR-CD/val/A/val_8.png', './LEVIR-CD/val/A/val_9.png']

dataset [ChangeDetectionDataset] was created

tcmalloc: large alloc 2147483648 bytes == 0x55839a3a0000 @  0x7f010397db6b 0x7f010399d379 0x7f0003182cde 0x7f0003184452 0x7f00551abcf3 0x7f0055233158 0x7f005590a49f 0x7f00558ea870 0x7f00556d548a 0x7f005522429d 0x7f0055a03aca 0x7f00558e670e 0x7f00554abd17 0x7f0056e0e7c4 0x7f0056e0ec8d 0x7f00555216e8 0x7f00552223d5 0x7f0055a8a970 0x7f00557d7069 0x7f00fe5e32c3 0x7f00fe73d04e 0x55832f87f4b0 0x55832f970e1d 0x55832f8f2e99 0x55832f8ed9ee 0x55832f880bda 0x55832f8ef737 0x55832f880afa 0x55832f8ee915 0x55832f8ed9ee 0x55832f8ed6f3
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    miou_current = val(opt, model)
  File "train.py", line 86, in val
    score = model.test(val=True)           # run inference
  File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/models/CDF0_model.py", line 79, in test
    metrics.update(self.L.detach().cpu().numpy(), pred.detach().cpu().numpy())
  File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/util/metrics.py", line 121, in update
    self.confusion_matrix += self.__fast_hist(lt.flatten(), lp.flatten())
  File "/content/drive/MyDrive/Experiment/codes/33_STANet/STANet/util/metrics.py", line 108, in __fast_hist
    hist = np.bincount(self.num_classes * label_gt[mask].astype(int) + label_pred[mask],
IndexError: boolean index did not match indexed array along dimension 0; dimension is 67108864 but corresponding boolean dimension is 1048576.`

**Comment by weizhiliang0520** [comment]
> 有遇到过，最后把图像裁剪成256x256输入，再训练就没这个问题了


你好，前面base的模型已经跑通. 但是现在换到-- lr 0.0002 --model CDFA0  --SA_mode BAM --batch_size 2  crop_size 256, 但是结果都还是先和隔壁的问题一样， CUDA out of memory. Tried to allocate 256.00 GiB 我的 GPU 1: 10.76 GiB，ds设置为1。出现上面的问题是跑了一个epoch以后，才出现的。如果batch_size =8, 第一个epoch都不能跑。 请问你有什么建议？

还有，您说的剪切是不是代码中的crop size=256，还是要自己先在其他地方剪切呢？
