### ISSUE TITLE
bug report in the testing phase

### ISSUE THREAD

**Issue by ipScore** [justchenhao/STANet#7]
Hi, @justchenhao 

```
Traceback (most recent call last):
  File "/workspace/pyroom/STANet/val.py", line 100, in <module>
    val(opt)
  File "/workspace/pyroom/STANet/val.py", line 64, in val
    score = model.test(val=True)           # run inference return confusion_matrix
  File "/workspace/pyroom/STANet/models/CDFA_model.py", line 83, in test
    metrics.update(self.L.detach().cpu().numpy(), pred.detach().cpu().numpy())
AttributeError: 'CDFAModel' object has no attribute 'L'
```

1. 64th line of val.py:   `score = model.test(val=True)`
2. from 23th to 29th line of changedetection_dataset.py:
```
        self.istest = False
        if opt.phase == 'test':
            self.istest = True
        if not self.istest:
            self.L_paths = sorted(make_dataset(os.path.join(opt.dataroot, folder_L), opt.max_dataset_size))
```

when testing with `val=True`, dataset would not `load the labels self.L` so that it would raise a error.

**Comment by justchenhao** [comment]
Thanks for your carefulness. The `Val` mode is designed in the condition of having labels. While the `Test` mode can be used when you have not the label.

**Comment by ipScore** [comment]
@justchenhao  It is desired to return the `predicted change maps` with their `metric scores` in the testing phase.
