### ISSUE TITLE
AssertionError: X and Y should be the same shape

### ISSUE THREAD

**Issue by louxiantuo** [justchenhao/STANet#8]
Setting up a new session...
create web directory ./checkpoints\LEVIR-CDF0\web...
(epoch: 1, iters: 200, time: 0.033, data: 4.480) f: 1.110
(epoch: 1, iters: 400, time: 0.048, data: 1.109) f: 0.909
Traceback (most recent call last):
  File "./train.py", line 148, in <module>
    visualizer.plot_current_losses(epoch, float(epoch_iter) / dataset_size, losses)
  File "D:\xunleiDownload\STANet-master\util\visualizer.py", line 212, in plot_current_losses
    win=self.display_id)
  File "D:\Software\anaconda3\envs\pytorch_gpu\lib\site-packages\visdom\__init__.py", line 389, in wrapped_f
    return f(*args, **kwargs)
  File "D:\Software\anaconda3\envs\pytorch_gpu\lib\site-packages\visdom\__init__.py", line 1694, in line
    assert X.shape == Y.shape, 'X and Y should be the same shape'
AssertionError: X and Y should be the same shape

Please help me what should I do next.

**Comment by justchenhao** [comment]
It was reported by some other people. They said that it was the visdom version problem. You can change its version to 0.1.8.1 and then it can run normally.

**Comment by louxiantuo** [comment]
Thanks，because of visdom version problem I change the following code:

if aspect_ratio > 1.0:
    #im = imresize(im, (h, int(w * aspect_ratio)), interp='bicubic')
    im = np.array(Image.fromarray(im).resize((h,int(w*aspect_ratio))))
    #im = np.array(Image.fromarray(im).resize((h, int(w * aspect_ratio))))
if aspect_ratio < 1.0:
    #im = imresize(im, (int(h / aspect_ratio), w), interp='bicubic')
    im = np.array(Image.fromarray(im).resize((int(h/aspect_ratio),w)))

maybe the problem occurred from here.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: justchenhao<mailto:notifications@github.com>
发送时间: 2020年6月11日 21:01
收件人: justchenhao/STANet<mailto:STANet@noreply.github.com>
抄送: louxiantuo<mailto:louxiantuo@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [justchenhao/STANet] AssertionError: X and Y should be the same shape (#8)


It was reported by some other people. They said that it was the visdom version problem. You can change its version to 0.1.8.1 and then it can run normally.

―

**Comment by hktxt** [comment]
`pip uninstall visdom`
then
`pip install visdom==0.1.8.1`

**Comment by justchenhao** [comment]
Close for now. This issue has been solved.
